// ── Enchantment tables ────────────────────────────────────────────────────────

/** Bedrock edition numeric enchantment ID → display name */
export const BEDROCK_ENCHANT: Record<number, string> = {
  0: "Protection",
  1: "Fire Protection",
  2: "Feather Falling",
  3: "Blast Protection",
  4: "Projectile Protection",
  5: "Thorns",
  6: "Respiration",
  7: "Depth Strider",
  8: "Aqua Affinity",
  9: "Sharpness",
  10: "Smite",
  11: "Bane of Arthropods",
  12: "Knockback",
  13: "Fire Aspect",
  14: "Looting",
  15: "Efficiency",
  16: "Silk Touch",
  17: "Unbreaking",
  18: "Fortune",
  19: "Power",
  20: "Punch",
  21: "Flame",
  22: "Infinity",
  23: "Luck of the Sea",
  24: "Lure",
  25: "Frost Walker",
  26: "Mending",
  27: "Curse of Binding",
  28: "Curse of Vanishing",
  29: "Impaling",
  30: "Riptide",
  31: "Loyalty",
  32: "Channeling",
  33: "Multishot",
  34: "Piercing",
  35: "Quick Charge",
  36: "Soul Speed",
  37: "Swift Sneak",
  38: "Wind Burst",
  39: "Breach",
  40: "Density",
}

/** Java edition string enchantment ID → display name */
export const JAVA_ENCHANT: Record<string, string> = {
  "minecraft:protection": "Protection",
  "minecraft:fire_protection": "Fire Protection",
  "minecraft:feather_falling": "Feather Falling",
  "minecraft:blast_protection": "Blast Protection",
  "minecraft:projectile_protection": "Projectile Protection",
  "minecraft:thorns": "Thorns",
  "minecraft:respiration": "Respiration",
  "minecraft:depth_strider": "Depth Strider",
  "minecraft:aqua_affinity": "Aqua Affinity",
  "minecraft:sharpness": "Sharpness",
  "minecraft:smite": "Smite",
  "minecraft:bane_of_arthropods": "Bane of Arthropods",
  "minecraft:knockback": "Knockback",
  "minecraft:fire_aspect": "Fire Aspect",
  "minecraft:looting": "Looting",
  "minecraft:efficiency": "Efficiency",
  "minecraft:silk_touch": "Silk Touch",
  "minecraft:unbreaking": "Unbreaking",
  "minecraft:fortune": "Fortune",
  "minecraft:power": "Power",
  "minecraft:punch": "Punch",
  "minecraft:flame": "Flame",
  "minecraft:infinity": "Infinity",
  "minecraft:luck_of_the_sea": "Luck of the Sea",
  "minecraft:lure": "Lure",
  "minecraft:frost_walker": "Frost Walker",
  "minecraft:mending": "Mending",
  "minecraft:binding_curse": "Curse of Binding",
  "minecraft:vanishing_curse": "Curse of Vanishing",
  "minecraft:impaling": "Impaling",
  "minecraft:riptide": "Riptide",
  "minecraft:loyalty": "Loyalty",
  "minecraft:channeling": "Channeling",
  "minecraft:multishot": "Multishot",
  "minecraft:piercing": "Piercing",
  "minecraft:quick_charge": "Quick Charge",
  "minecraft:soul_speed": "Soul Speed",
  "minecraft:swift_sneak": "Swift Sneak",
  "minecraft:wind_burst": "Wind Burst",
  "minecraft:breach": "Breach",
  "minecraft:density": "Density",
}

export const ROMAN = ["", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]
export function toRoman(n: number): string {
  return n > 0 && n < ROMAN.length ? ROMAN[n] : String(n)
}

// ── Text colour maps ──────────────────────────────────────────────────────────

/** Minecraft §-code character → CSS hex colour */
export const MC_COLOR: Record<string, string> = {
  "0": "#000000",
  "1": "#0000AA",
  "2": "#00AA00",
  "3": "#00AAAA",
  "4": "#AA0000",
  "5": "#AA00AA",
  "6": "#FFAA00",
  "7": "#AAAAAA",
  "8": "#555555",
  "9": "#5555FF",
  a: "#55FF55",
  b: "#55FFFF",
  c: "#FF5555",
  d: "#FF55FF",
  e: "#FFFF55",
  f: "#FFFFFF",
}

/** Java JSON text component "color" named value → CSS hex */
export const JSON_COLOR: Record<string, string> = {
  black: "#000000",
  dark_blue: "#0000AA",
  dark_green: "#00AA00",
  dark_aqua: "#00AAAA",
  dark_red: "#AA0000",
  dark_purple: "#AA00AA",
  gold: "#FFAA00",
  gray: "#AAAAAA",
  dark_gray: "#555555",
  blue: "#5555FF",
  green: "#55FF55",
  aqua: "#55FFFF",
  red: "#FF5555",
  light_purple: "#FF55FF",
  yellow: "#FFFF55",
  white: "#FFFFFF",
}

// ── Item helpers ──────────────────────────────────────────────────────────────

/** "minecraft:diamond_sword" → "Diamond Sword" */
export function itemDisplayName(id: string): string {
  return id
    .replace(/^minecraft:/, "")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

/** Material-based background colour for the icon fallback box. */
export function itemIconColor(id: string): string {
  const s = id.replace(/^minecraft:/, "").toLowerCase()
  if (s === "air") return "#252525"
  if (/netherite/.test(s)) return "#524042"
  if (/diamond/.test(s)) return "#3DD4D4"
  if (/emerald/.test(s)) return "#17DD62"
  if (/(golden?_|^gold_)/.test(s)) return "#FABD27"
  if (/iron/.test(s)) return "#B0AFA9"
  if (/chainmail|chain/.test(s)) return "#6A6A6A"
  if (/turtle|scute/.test(s)) return "#51A846"
  if (/leather/.test(s)) return "#9E5229"
  if (/stone|cobble|andesite|diorite|granite/.test(s)) return "#8C8C7E"
  if (/wood(en)?|plank|oak|birch|spruce|jungle|acacia|dark_oak|mangrove|cherry|bamboo|crimson|warped/.test(s))
    return "#8B6220"
  if (/enchanted_book/.test(s)) return "#8A2BE2"
  if (/crossbow|bow|arrow/.test(s)) return "#C96808"
  if (/sword/.test(s)) return "#E64A19"
  if (/axe|pickaxe|shovel|hoe/.test(s)) return "#757575"
  if (/helmet|chestplate|leggings|boots/.test(s)) return "#5C6BC0"
  if (/elytra/.test(s)) return "#7986CB"
  if (/trident/.test(s)) return "#2196F3"
  if (/totem/.test(s)) return "#FFAB40"
  if (/potion|splash|lingering/.test(s)) return "#7B1FA2"
  if (/ender|chorus/.test(s)) return "#5C2D8C"
  if (/apple|carrot|potato|beetroot|melon|berry|bread|cake|cookie|honey|mushroom|pumpkin_pie/.test(s)) return "#8BC34A"
  if (/fish|cod|salmon|tropical/.test(s)) return "#1565C0"
  if (/fire|blaze|magma/.test(s)) return "#F4511E"
  if (/book|paper|written/.test(s)) return "#E8DCC2"
  if (/map|compass|clock/.test(s)) return "#5D4037"
  if (/music_disc/.test(s)) return "#1B5E20"
  if (/shield/.test(s)) return "#8B7355"
  return "#78909C"
}

/**
 * Sprite sheet positions in items.webp.
 * Sheet: 256 × 1072 px  ·  16 × 16 px tiles  ·  16 cols × 67 rows.
 * Format: [col, row].  CSS offset = [-col*16 px, -row*16 px].
 *
 * To populate: open items.webp in an image editor, find the tile at grid
 * coordinates [col, row] (0-indexed) and add it here.
 * Example: 'minecraft:diamond_sword': [4, 5]
 */
export const SPRITE_POS: Partial<Record<string, readonly [number, number]>> = {
  "minecraft:acacia_boat": [13,36],
  "minecraft:acacia_chest_boat": [14,56],
  "minecraft:armor_stand": [5,32],
  "minecraft:bamboo_raft": [9,58],
  "minecraft:bamboo_chest_boat": [10,58],
  "minecraft:beetroot_seeds": [9,36],
  "minecraft:birch_boat": [14,36],
  "minecraft:birch_chest_boat": [15,56],
  "minecraft:experience_bottle": [7,32],
  "minecraft:bow": [5,1],
  "minecraft:bucket": [7,28],
  "minecraft:axolotl_bucket": [7,54],
  "minecraft:cod_bucket": [5,38],
  "minecraft:pufferfish_bucket": [6,38],
  "minecraft:salmon_bucket": [7,38],
  "minecraft:tadpole_bucket": [3,56],
  "minecraft:tropical_fish_bucket": [8,38],
  "minecraft:carrot": [10,30],
  "minecraft:cherry_boat": [9,60],
  "minecraft:cherry_chest_boat": [10,60],
  "minecraft:cocoa_beans": [10,36],
  "minecraft:crossbow": [2,23],
  "minecraft:dark_oak_boat": [15,36],
  "minecraft:dark_oak_chest_boat": [0,57],
  "minecraft:egg": [3,31],
  "minecraft:end_crystal": [12,32],
  "minecraft:ender_pearl": [14,34],
  "minecraft:ender_eye": [0,34],
  "minecraft:fire_charge": [13,28],
  "minecraft:firework_rocket": [13,32],
  "minecraft:fishing_rod": [14,28],
  "minecraft:flint_and_steel": [15,28],
  "minecraft:glow_berries": [11,54],
  "minecraft:glow_item_frame": [10,54],
  "minecraft:item_frame": [0,33],
  "minecraft:jungle_boat": [0,37],
  "minecraft:jungle_chest_boat": [1,57],
  "minecraft:kelp": [1,21],
  "minecraft:lava_bucket": [8,29],
  "minecraft:lead": [1,33],
  "minecraft:lingering_potion": [14,39],
  "minecraft:mangrove_boat": [8,57],
  "minecraft:mangrove_chest_boat": [4,57],
  "minecraft:melon_seeds": [14,3],
  "minecraft:minecart": [1,37],
  "minecraft:chest_minecart": [2,37],
  "minecraft:command_block_minecart": [3,37],
  "minecraft:furnace_minecart": [4,37],
  "minecraft:hopper_minecart": [5,37],
  "minecraft:tnt_minecart": [6,37],
  "minecraft:nether_wart": [13,7],
  "minecraft:oak_boat": [7,37],
  "minecraft:oak_chest_boat": [2,57],
  "minecraft:painting": [3,33],
  "minecraft:pale_oak_boat": [10,65],
  "minecraft:pale_oak_chest_boat": [11,65],
  "minecraft:pitcher_pod": [13,61],
  "minecraft:potato": [14,31],
  "minecraft:powder_snow_bucket": [5,54],
  "minecraft:pumpkin_seeds": [13,3],
  "minecraft:redstone": [1,36],
  "minecraft:snowball": [2,28],
  "minecraft:splash_potion": [11,26],
  "minecraft:spruce_boat": [8,37],
  "minecraft:spruce_chest_boat": [5,57],
  "minecraft:string": [5,36],
  "minecraft:sweet_berries": [6,24],
  "minecraft:torchflower_seeds": [15,59],
  "minecraft:trident": [0,21],
  "minecraft:water_bucket": [14,29],
  "minecraft:wheat_seeds": [9,0],
  "minecraft:wind_charge": [15,23],
  "minecraft:amethyst_shard": [15,52],
  "minecraft:apple": [3,30],
  "minecraft:arrow": [5,2],
  "minecraft:baked_potato": [4,30],
  "minecraft:beetroot": [6,30],
  "minecraft:beetroot_soup": [7,30],
  "minecraft:black_bundle": [3,53],
  "minecraft:black_dye": [4,23],
  "minecraft:black_harness": [15,23],
  "minecraft:blue_bundle": [3,53],
  "minecraft:blue_dye": [5,23],
  "minecraft:blue_harness": [15,23],
  "minecraft:bone": [7,34],
  "minecraft:bone_meal": [8,34],
  "minecraft:book": [12,33],
  "minecraft:writable_book": [6,32],
  "minecraft:bowl": [13,33],
  "minecraft:bread": [8,30],
  "minecraft:brown_bundle": [3,53],
  "minecraft:brown_dye": [6,23],
  "minecraft:brown_harness": [15,23],
  "minecraft:brush": [4,60],
  "minecraft:carrot_on_a_stick": [8,28],
  "minecraft:chainmail_boots": [15,1],
  "minecraft:chainmail_chestplate": [15,2],
  "minecraft:chainmail_helmet": [15,3],
  "minecraft:chainmail_leggings": [15,16],
  "minecraft:chorus_fruit": [12,30],
  "minecraft:compass": [2,55],
  "minecraft:cooked_chicken": [14,30],
  "minecraft:cooked_fish": [9,21],
  "minecraft:cooked_mutton": [15,30],
  "minecraft:cooked_porkchop": [0,31],
  "minecraft:cooked_rabbit": [1,31],
  "minecraft:cooked_salmon": [10,21],
  "minecraft:cookie": [2,31],
  "minecraft:copper_axe": [15,23],
  "minecraft:copper_boots": [15,23],
  "minecraft:copper_chestplate": [15,23],
  "minecraft:copper_helmet": [15,23],
  "minecraft:copper_hoe": [15,23],
  "minecraft:copper_horse_armor": [15,23],
  "minecraft:copper_leggings": [15,23],
  "minecraft:copper_nautilus_armor": [15,23],
  "minecraft:copper_pickaxe": [15,23],
  "minecraft:copper_shovel": [15,23],
  "minecraft:copper_sword": [15,23],
  "minecraft:copper_spear": [15,23],
  "minecraft:cyan_bundle": [3,53],
  "minecraft:cyan_dye": [9,37],
  "minecraft:cyan_harness": [15,23],
  "minecraft:debug_stick": [5,3],
  "minecraft:diamond_axe": [9,28],
  "minecraft:diamond_boots": [8,25],
  "minecraft:diamond_chestplate": [9,25],
  "minecraft:diamond_helmet": [10,25],
  "minecraft:diamond_hoe": [10,28],
  "minecraft:diamond_horse_armor": [11,25],
  "minecraft:diamond_nautilus_armor": [15,23],
  "minecraft:diamond_leggings": [12,25],
  "minecraft:diamond_pickaxe": [11,28],
  "minecraft:diamond_shovel": [12,28],
  "minecraft:diamond_sword": [14,27],
  "minecraft:diamond_spear": [15,23],
  "minecraft:dried_kelp": [2,21],
  "minecraft:elytra": [13,25],
  "minecraft:empty_map": [8,33],
  "minecraft:enchanted_book": [11,32],
  "minecraft:enchanted_golden_apple": [4,31],
  "minecraft:goat_horn": [13,52],
  "minecraft:glass_bottle": [2,34],
  "minecraft:glow_ink_sac": [9,54],
  "minecraft:gold_ingot": [3,35],
  "minecraft:golden_apple": [5,31],
  "minecraft:golden_axe": [0,29],
  "minecraft:golden_boots": [14,25],
  "minecraft:golden_carrot": [6,31],
  "minecraft:golden_chestplate": [15,25],
  "minecraft:golden_helmet": [0,26],
  "minecraft:golden_hoe": [1,29],
  "minecraft:golden_horse_armor": [1,26],
  "minecraft:golden_leggings": [2,26],
  "minecraft:golden_nautilus_armor": [15,23],
  "minecraft:golden_pickaxe": [2,29],
  "minecraft:golden_shovel": [3,29],
  "minecraft:golden_sword": [15,27],
  "minecraft:golden_spear": [15,23],
  "minecraft:gray_bundle": [3,53],
  "minecraft:gray_dye": [10,37],
  "minecraft:gray_harness": [15,23],
  "minecraft:green_bundle": [3,53],
  "minecraft:green_dye": [11,37],
  "minecraft:green_harness": [15,23],
  "minecraft:honeycomb": [6,42],
  "minecraft:honey_bottle": [4,42],
  "minecraft:ink_sac": [6,35],
  "minecraft:iron_axe": [4,29],
  "minecraft:iron_boots": [3,26],
  "minecraft:iron_chestplate": [4,26],
  "minecraft:iron_helmet": [5,26],
  "minecraft:iron_hoe": [5,29],
  "minecraft:iron_horse_armor": [6,26],
  "minecraft:iron_ingot": [7,35],
  "minecraft:iron_leggings": [7,26],
  "minecraft:iron_nautilus_armor": [15,23],
  "minecraft:iron_pickaxe": [6,29],
  "minecraft:iron_shovel": [7,29],
  "minecraft:iron_sword": [0,28],
  "minecraft:iron_spear": [15,23],
  "minecraft:knowledge_book": [9,33],
  "minecraft:lapis_lazuli": [8,35],
  "minecraft:leather_boots": [8,26],
  "minecraft:leather_helmet": [9,26],
  "minecraft:leather_horse_armor": [2,10],
  "minecraft:leather_leggings": [12,26],
  "minecraft:leather_chestplate": [10,26],
  "minecraft:light_blue_bundle": [3,53],
  "minecraft:light_blue_dye": [12,37],
  "minecraft:light_blue_harness": [15,23],
  "minecraft:light_gray_bundle": [3,53],
  "minecraft:light_gray_dye": [13,37],
  "minecraft:light_gray_harness": [15,23],
  "minecraft:lime_bundle": [3,53],
  "minecraft:lime_dye": [14,37],
  "minecraft:lime_harness": [15,23],
  "minecraft:mace": [15,23],
  "minecraft:magenta_bundle": [3,53],
  "minecraft:magenta_dye": [15,37],
  "minecraft:magenta_harness": [15,23],
  "minecraft:filled_map": [7,33],
  "minecraft:melon_slice": [7,31],
  "minecraft:milk_bucket": [8,31],
  "minecraft:mushroom_stew": [9,31],
  "minecraft:music_disc_5": [12,57],
  "minecraft:music_disc_11": [7,36],
  "minecraft:music_disc_13": [0,15],
  "minecraft:music_disc_blocks": [2,15],
  "minecraft:music_disc_cat": [1,15],
  "minecraft:music_disc_chirp": [3,15],
  "minecraft:music_disc_creator": [12,65],
  "minecraft:music_disc_far": [4,15],
  "minecraft:music_disc_mall": [5,15],
  "minecraft:music_disc_mellohi": [6,15],
  "minecraft:music_disc_otherside": [3,55],
  "minecraft:music_disc_pigstep": [13,51],
  "minecraft:music_disc_precipice": [2,64],
  "minecraft:music_disc_stal": [7,15],
  "minecraft:music_disc_strad": [8,15],
  "minecraft:music_disc_wait": [11,15],
  "minecraft:music_disc_ward": [9,15],
  "minecraft:name_tag": [2,33],
  "minecraft:netherite_axe": [6,51],
  "minecraft:netherite_boots": [1,51],
  "minecraft:netherite_chestplate": [2,51],
  "minecraft:netherite_helmet": [3,51],
  "minecraft:netherite_hoe": [7,51],
  "minecraft:netherite_leggings": [4,51],
  "minecraft:netherite_nautilus_armor": [15,23],
  "minecraft:netherite_pickaxe": [8,51],
  "minecraft:netherite_shovel": [9,51],
  "minecraft:netherite_sword": [5,51],
  "minecraft:netherite_spear": [15,23],
  "minecraft:ominous_bottle": [15,23],
  "minecraft:ominous_trial_key": [15,23],
  "minecraft:orange_bundle": [3,53],
  "minecraft:orange_dye": [0,38],
  "minecraft:orange_harness": [15,23],
  "minecraft:pink_bundle": [3,53],
  "minecraft:pink_dye": [1,38],
  "minecraft:pink_harness": [15,23],
  "minecraft:poisonous_potato": [11,31],
  "minecraft:potion": [0,25],
  "minecraft:pufferfish": [11,21],
  "minecraft:pumpkin_pie": [15,31],
  "minecraft:purple_bundle": [3,53],
  "minecraft:purple_dye": [2,38],
  "minecraft:purple_harness": [15,23],
  "minecraft:rabbit_stew": [1,32],
  "minecraft:beef": [5,30],
  "minecraft:chicken": [11,30],
  "minecraft:fish": [15,20],
  "minecraft:mutton": [10,31],
  "minecraft:porkchop": [13,31],
  "minecraft:rabbit": [0,32],
  "minecraft:salmon": [12,21],
  "minecraft:red_bundle": [3,53],
  "minecraft:red_dye": [3,38],
  "minecraft:red_harness": [15,23],
  "minecraft:rotten_flesh": [2,32],
  "minecraft:saddle": [5,33],
  "minecraft:shears": [9,29],
  "minecraft:shield": [1,28],
  "minecraft:spectral_arrow": [3,28],
  "minecraft:spider_eye": [4,36],
  "minecraft:spyglass": [3,54],
  "minecraft:cooked_beef": [13,30],
  "minecraft:stone_axe": [10,29],
  "minecraft:stone_hoe": [11,29],
  "minecraft:stone_pickaxe": [12,29],
  "minecraft:stone_shovel": [13,29],
  "minecraft:stone_sword": [4,28],
  "minecraft:stone_spear": [15,23],
  "minecraft:sugar": [3,32],
  "minecraft:suspicious_stew": [3,23],
  "minecraft:tipped_arrow": [8,54],
  "minecraft:totem_of_undying": [6,36],
  "minecraft:trial_key": [15,23],
  "minecraft:tropical_fish": [5,22],
  "minecraft:turtle_helmet": [4,21],
  "minecraft:warped_fungus_on_a_stick": [11,51],
  "minecraft:wheat": [12,36],
  "minecraft:white_bundle": [3,53],
  "minecraft:white_dye": [7,23],
  "minecraft:white_harness": [15,23],
  "minecraft:wolf_armor": [4,65],
  "minecraft:wooden_axe": [15,29],
  "minecraft:wooden_hoe": [0,30],
  "minecraft:wooden_pickaxe": [1,30],
  "minecraft:wooden_shovel": [2,30],
  "minecraft:wooden_sword": [6,28],
  "minecraft:wooden_spear": [15,23],
  "minecraft:written_book": [6,33],
  "minecraft:yellow_bundle": [3,53],
  "minecraft:yellow_dye": [4,38],
  "minecraft:yellow_harness": [15,23],
  "minecraft:angler_pottery_sherd": [12,60],
  "minecraft:archer_pottery_sherd": [0,60],
  "minecraft:armadillo_scute": [15,23],
  "minecraft:arms_up_pottery_sherd": [1,60],
  "minecraft:flower_banner_pattern": [14,23],
  "minecraft:creeper_banner_pattern": [14,23],
  "minecraft:skull_banner_pattern": [14,23],
  "minecraft:thing_banner_pattern": [14,23],
  "minecraft:field_masoned_banner_pattern": [14,23],
  "minecraft:bordure_indented_banner_pattern": [14,23],
  "minecraft:piglin_banner_pattern": [14,23],
  "minecraft:flow_banner_pattern": [14,23],
  "minecraft:guster_banner_pattern": [14,23],
  "minecraft:blade_pottery_sherd": [13,60],
  "minecraft:blaze_powder": [13,9],
  "minecraft:blaze_rod": [12,6],
  "minecraft:bolt_armor_trim_smithing_template": [13,65],
  "minecraft:breeze_rod": [15,23],
  "minecraft:brewer_pottery_sherd": [14,60],
  "minecraft:brick": [14,33],
  "minecraft:burn_pottery_sherd": [15,60],
  "minecraft:charcoal": [9,34],
  "minecraft:clay_ball": [10,34],
  "minecraft:clock": [1,55],
  "minecraft:coal": [11,34],
  "minecraft:coast_armor_trim_smithing_template": [3,59],
  "minecraft:copper_ingot": [5,53],
  "minecraft:copper_nugget": [15,23],
  "minecraft:danger_pottery_sherd": [0,61],
  "minecraft:diamond": [12,34],
  "minecraft:music_disc_5_fragment": [11,57],
  "minecraft:dragon_breath": [15,33],
  "minecraft:dune_armor_trim_smithing_template": [4,59],
  "minecraft:echo_shard": [6,57],
  "minecraft:emerald": [13,34],
  "minecraft:explorer_pottery_sherd": [1,61],
  "minecraft:eye_armor_trim_smithing_template": [5,59],
  "minecraft:feather": [15,34],
  "minecraft:fermented_spider_eye": [1,34],
  "minecraft:firework_star": [10,12],
  "minecraft:flint": [0,35],
  "minecraft:flow_armor_trim_smithing_template": [14,65],
  "minecraft:flow_pottery_sherd": [15,65],
  "minecraft:friend_pottery_sherd": [2,61],
  "minecraft:ghast_tear": [1,35],
  "minecraft:glistering_melon_slice": [3,34],
  "minecraft:glowstone_dust": [2,35],
  "minecraft:gold_nugget": [4,35],
  "minecraft:gunpowder": [5,35],
  "minecraft:guster_pottery_sherd": [0,66],
  "minecraft:heart_of_the_sea": [12,22],
  "minecraft:heart_pottery_sherd": [3,61],
  "minecraft:heartbreak_pottery_sherd": [4,61],
  "minecraft:host_armor_trim_smithing_template": [14,61],
  "minecraft:howl_pottery_sherd": [5,61],
  "minecraft:leather": [9,35],
  "minecraft:magma_cream": [4,34],
  "minecraft:miner_pottery_sherd": [6,61],
  "minecraft:mourner_pottery_sherd": [7,61],
  "minecraft:nautilus_shell": [13,22],
  "minecraft:nether_brick": [5,34],
  "minecraft:quartz": [10,35],
  "minecraft:nether_star": [11,35],
  "minecraft:netherite_ingot": [15,50],
  "minecraft:netherite_scrap": [0,51],
  "minecraft:netherite_upgrade_smithing_template": [6,59],
  "minecraft:paper": [6,34],
  "minecraft:phantom_membrane": [12,35],
  "minecraft:plenty_pottery_sherd": [8,61],
  "minecraft:popped_chorus_fruit": [12,31],
  "minecraft:prismarine_crystals": [13,35],
  "minecraft:prismarine_shard": [14,35],
  "minecraft:prize_pottery_sherd": [2,60],
  "minecraft:rabbit_hide": [0,36],
  "minecraft:rabbit_foot": [15,35],
  "minecraft:raiser_armor_trim_smithing_template": [15,61],
  "minecraft:raw_copper": [14,54],
  "minecraft:raw_gold": [15,54],
  "minecraft:raw_iron": [0,55],
  "minecraft:recovery_compass": [7,57],
  "minecraft:rib_armor_trim_smithing_template": [7,59],
  "minecraft:scrape_pottery_sherd": [1,66],
  "minecraft:turtle_scute": [3,21],
  "minecraft:sentry_armor_trim_smithing_template": [8,59],
  "minecraft:shaper_armor_trim_smithing_template": [0,62],
  "minecraft:sheaf_pottery_sherd": [9,61],
  "minecraft:shelter_pottery_sherd": [10,61],
  "minecraft:shulker_shell": [2,36],
  "minecraft:silence_armor_trim_smithing_template": [1,62],
  "minecraft:skull_pottery_sherd": [3,60],
  "minecraft:slime_ball": [3,36],
  "minecraft:snort_pottery_sherd": [11,61],
  "minecraft:spire_armor_trim_smithing_template": [10,59],
  "minecraft:stick": [5,3],
  "minecraft:tide_armor_trim_smithing_template": [11,59],
  "minecraft:vex_armor_trim_smithing_template": [12,59],
  "minecraft:ward_armor_trim_smithing_template": [13,59],
  "minecraft:wayfinder_armor_trim_smithing_template": [2,62],
  "minecraft:wild_armor_trim_smithing_template": [14,59],
  "minecraft:allay_spawn_egg": [11,56],
  "minecraft:armadillo_spawn_egg": [15,23],
  "minecraft:axolotl_spawn_egg": [6,54],
  "minecraft:bat_spawn_egg": [1,18],
  "minecraft:bee_spawn_egg": [1,43],
  "minecraft:blaze_spawn_egg": [2,18],
  "minecraft:bogged_spawn_egg": [15,23],
  "minecraft:breeze_spawn_egg": [15,23],
  "minecraft:camel_spawn_egg": [11,58],
  "minecraft:cat_spawn_egg": [1,23],
  "minecraft:cave_spider_spawn_egg": [3,18],
  "minecraft:chicken_spawn_egg": [4,18],
  "minecraft:cod_spawn_egg": [13,21],
  "minecraft:copper_golem_spawn_egg": [15,23],
  "minecraft:cow_spawn_egg": [5,18],
  "minecraft:creaking_spawn_egg": [15,23],
  "minecraft:creeper_spawn_egg": [6,18],
  "minecraft:dolphin_spawn_egg": [14,22],
  "minecraft:donkey_spawn_egg": [7,18],
  "minecraft:drowned_spawn_egg": [9,22],
  "minecraft:elder_guardian_spawn_egg": [8,18],
  "minecraft:ender_dragon_spawn_egg": [14,58],
  "minecraft:enderman_spawn_egg": [9,18],
  "minecraft:endermite_spawn_egg": [10,18],
  "minecraft:evoker_spawn_egg": [11,18],
  "minecraft:fox_spawn_egg": [15,0],
  "minecraft:frog_spawn_egg": [4,56],
  "minecraft:ghast_spawn_egg": [12,18],
  "minecraft:glow_squid_spawn_egg": [13,54],
  "minecraft:goat_spawn_egg": [14,52],
  "minecraft:guardian_spawn_egg": [13,18],
  "minecraft:hoglin_spawn_egg": [3,44],
  "minecraft:horse_spawn_egg": [14,18],
  "minecraft:husk_spawn_egg": [15,18],
  "minecraft:iron_golem_spawn_egg": [15,58],
  "minecraft:llama_spawn_egg": [0,19],
  "minecraft:magma_cube_spawn_egg": [1,19],
  "minecraft:mooshroom_spawn_egg": [2,19],
  "minecraft:mule_spawn_egg": [3,19],
  "minecraft:npc_spawn_egg": [13,24],
  "minecraft:ocelot_spawn_egg": [4,19],
  "minecraft:panda_spawn_egg": [8,24],
  "minecraft:parrot_spawn_egg": [8,19],
  "minecraft:phantom_spawn_egg": [8,21],
  "minecraft:pig_spawn_egg": [5,19],
  "minecraft:piglin_spawn_egg": [10,51],
  "minecraft:piglin_brute_spawn_egg": [8,52],
  "minecraft:pillager_spawn_egg": [9,24],
  "minecraft:polar_bear_spawn_egg": [6,19],
  "minecraft:pufferfish_spawn_egg": [14,21],
  "minecraft:rabbit_spawn_egg": [7,19],
  "minecraft:ravager_spawn_egg": [7,24],
  "minecraft:salmon_spawn_egg": [15,21],
  "minecraft:sheep_spawn_egg": [9,19],
  "minecraft:shulker_spawn_egg": [10,19],
  "minecraft:silverfish_spawn_egg": [11,19],
  "minecraft:skeleton_horse_spawn_egg": [13,19],
  "minecraft:skeleton_spawn_egg": [12,19],
  "minecraft:slime_spawn_egg": [14,19],
  "minecraft:sniffer_spawn_egg": [11,60],
  "minecraft:snow_golem_spawn_egg": [0,59],
  "minecraft:spider_spawn_egg": [15,19],
  "minecraft:squid_spawn_egg": [0,20],
  "minecraft:stray_spawn_egg": [1,20],
  "minecraft:strider_spawn_egg": [12,51],
  "minecraft:tadpole_spawn_egg": [5,56],
  "minecraft:trader_llama_spawn_egg": [1,25],
  "minecraft:tropical_fish_spawn_egg": [4,22],
  "minecraft:turtle_spawn_egg": [7,21],
  "minecraft:vex_spawn_egg": [2,20],
  "minecraft:villager_spawn_egg": [3,20],
  "minecraft:vindicator_spawn_egg": [4,20],
  "minecraft:wandering_trader_spawn_egg": [2,25],
  "minecraft:warden_spawn_egg": [12,56],
  "minecraft:witch_spawn_egg": [5,20],
  "minecraft:wither_skeleton_spawn_egg": [6,20],
  "minecraft:wither_spawn_egg": [1,59],
  "minecraft:wolf_spawn_egg": [7,20],
  "minecraft:zoglin_spawn_egg": [1,52],
  "minecraft:zombie_horse_spawn_egg": [9,20],
  "minecraft:zombie_spawn_egg": [8,20],
  "minecraft:zombie_villager_spawn_egg": [11,20],
  "minecraft:zombified_piglin_spawn_egg": [10,20],
  "minecraft:agent_spawn_egg": [10,24],
  "minecraft:antidote": [13,45],
  "minecraft:black_balloon": [0,46],
  "minecraft:bleach": [4,46],
  "minecraft:blue_balloon": [6,46],
  "minecraft:blue_glow_stick": [9,46],
  "minecraft:blue_sparkler": [11,46],
  "minecraft:board": [14,17],
  "minecraft:brown_balloon": [13,46],
  "minecraft:brown_glow_stick": [0,47],
  "minecraft:camera": [0,27],
  "minecraft:compound": [9,50],
  "minecraft:cyan_balloon": [3,47],
  "minecraft:cyan_glow_stick": [4,47],
  "minecraft:elixir": [9,47],
  "minecraft:eye_drops": [10,47],
  "minecraft:gray_balloon": [12,47],
  "minecraft:gray_glow_stick": [13,47],
  "minecraft:green_balloon": [14,47],
  "minecraft:green_glow_stick": [1,48],
  "minecraft:green_sparkler": [3,48],
  "minecraft:ice_bomb": [2,42],
  "minecraft:light_blue_balloon": [9,48],
  "minecraft:light_blue_glow_stick": [10,48],
  "minecraft:lime_balloon": [15,48],
  "minecraft:lime_glow_stick": [0,49],
  "minecraft:magenta_balloon": [1,49],
  "minecraft:magenta_glow_stick": [2,49],
  "minecraft:orange_balloon": [4,49],
  "minecraft:orange_glow_stick": [7,49],
  "minecraft:orange_sparkler": [10,45],
  "minecraft:photo": [4,55],
  "minecraft:pink_balloon": [9,49],
  "minecraft:pink_glow_stick": [10,49],
  "minecraft:portfolio": [11,17],
  "minecraft:poster": [13,17],
  "minecraft:purple_balloon": [11,49],
  "minecraft:purple_glow_stick": [14,49],
  "minecraft:purple_sparkler": [0,50],
  "minecraft:red_balloon": [2,50],
  "minecraft:red_glow_stick": [5,50],
  "minecraft:red_sparkler": [7,50],
  "minecraft:silver_balloon": [11,48],
  "minecraft:slate": [12,17],
  "minecraft:super_fertilizer": [3,42],
  "minecraft:tonic": [10,50],
  "minecraft:white_balloon": [7,45],
  "minecraft:white_glow_stick": [8,45],
  "minecraft:yellow_balloon": [12,50],
  "minecraft:yellow_glow_stick": [14,50],
  "minecraft:ruby": [10,10],
  "minecraft:copper_horn": [13,56],
  "minecraft:horse_saddle": [1,9],
  "minecraft:studded_helmet": [7,42],
  "minecraft:studded_chestplate": [13,15],
  "minecraft:studded_leggings": [8,42],
  "minecraft:studded_boots": [9,42],
  "minecraft:quiver": [6,2],
  "minecraft:3d": [4,25],
  "minecraft:a_very_fine_item": [2,52],
  "minecraft:ankle_monitor": [12,20],
  "minecraft:arrow_of_big": [10,63],
  "minecraft:arrow_of_small": [11,63],
  "minecraft:banner_pattern_new_thing": [15,23],
  "minecraft:blue_key": [5,25],
  "minecraft:bit": [4,62],
  "minecraft:bottle_of_entity": [6,63],
  "minecraft:bottle_of_void": [7,63],
  "minecraft:byte_tag": [15,23],
  "minecraft:compound_tag": [15,23],
  "minecraft:double_tag": [15,23],
  "minecraft:float_tag": [15,23],
  "minecraft:footprint": [3,52],
  "minecraft:int_tag": [15,23],
  "minecraft:la_baguette": [12,61],
  "minecraft:le_tricolore": [3,62],
  "minecraft:left_curly": [15,23],
  "minecraft:left_square": [15,23],
  "minecraft:lingering_potion_of_big": [12,63],
  "minecraft:lingering_potion_of_small": [13,63],
  "minecraft:list_tag": [15,23],
  "minecraft:long_tag": [15,23],
  "minecraft:longer_string": [8,63],
  "minecraft:dupe_hack": [15,23],
  "minecraft:moon_cow_spawn_egg": [9,64],
  "minecraft:name": [15,23],
  "minecraft:obsidian_boat": [3,25],
  "minecraft:potion_of_big": [14,63],
  "minecraft:potion_of_small": [15,63],
  "minecraft:reality_vision": [13,20],
  "minecraft:red_key": [6,25],
  "minecraft:right_curly": [15,23],
  "minecraft:right_square": [15,23],
  "minecraft:short_tag": [15,23],
  "minecraft:smarter_watch": [14,20],
  "minecraft:splash_bottle_of_entity": [9,63],
  "minecraft:splash_potion_of_big": [0,64],
  "minecraft:splash_potion_of_small": [1,64],
  "minecraft:sssyntax_error": [15,23],
  "minecraft:string_tag": [15,23],
  "minecraft:tag": [15,23],
  "minecraft:yellow_key": [7,25]
}